[package]
name = "rusty"
version = "0.1.0"
edition = "2021"
authors = ["Carsten Gasch <carsten.gasch@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "0.8.7"
legion = "0.4.0"
